server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:identity
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect